language: node_js
node_js:
    - stable
cache:
    directories:
        - node_modules
before_deploy:
    - yarn build
    - rm -rf node_modules/
jobs:
    include:
        - stage: Tests
          name: Lint
          script: yarn lint
        - stage: deploy
          if: branch = 48-deploy-ghpages
          name: Deploy to Github Pages
          script: skip
          deploy:
              provider: pages
              skip_cleanup: true
              github_token: '$github_token'
              local_dir: docs
              on:
                  branch: 48-deploy-ghpages
env:
    matrix:
        - secure: SHuNDXHn7YpxLUxbQO4XPc2I3X03FR4tIyyxmaPOmSe0jnH0NQ67w25bFbn4OAC9/QKZWeg5UCxnGx/8CPEmX2PxMbBPxBT2RnTtJxxJ5+GbdoeFvQ3T3dwLBixJDJmakHwFU/tlhGzb1InVXDPmpmnRn224nKUnZlZM3+unpeo+I1aqrrY2E5gOenFlksM/I1lYkTfYOG2MzVpkL7Kzn9BTep0HDoUxpo6zjk5cFb1ewIhgDvNKY6BmNF8kA5wSC9+LXOIQWoUHFOssZ0U/y3nF/2UA0kQeP1/sqVMRwPqIqUvlpQru0KEuSZ8JApJippwwg5Z2Ah3YmOriCRZyh9OG0WmxMvNDqy1nwfHBQMs6MkJblaRU278QxLO+QJoQInD7rvju4nag2WwntxJahbDPac+QoyG5z1h6vQfgZlI/ySd9kWGv4qTtLpVsBOQsrnpFzYN8kmHUb46Hck5HSHNqTSnsnLqeKQYno4/6qiAiT60RtN3K0qOnmqsDR7xT9pVSziI04wN+Ed99nBcjc1Hqy8teDQN3n7apg+WKBWzBmD3oJqJ9bwURZW4fFBKXlHRTMVkK/xqRwQ75kRrdj2i9vhIZKjSlLpNi0WYNm4N+QlY+JuUmXexL1P7gNgitneWXXfH5ELU+T6cGn54pZYA2topqmGQmbMo1Slf2aro=
        - secure: fGC7i6i6DhHyb2XjsqQllZryN7hpUf58FDhOmi32yDGVqAmdBN4jsp1cAsaMa8GgNjtKq4I+XjnHIUY9ZkZmrmun7V49ezBXt9F0+3QA835ItrwoK1yYdWNjlqxGDNRa+fWqzFkASHbH7FrgDWOW1Lqjev+1H5cFZRNenN44yiW/XdJE9tClIBfTdS2hAKs8q4gOW73mc1mrXIaxzeo5E2Xe1vFtZHylQwwlrFmKdGlHx863JTcWF6HvWxFOGqY23QsqBEuBNYCrOPwvIOtP+crc7k4Iyjk4gf3jqij2XvXHGFqdRzQZ72eLohJVwZeF5lu5zRVwEfTHRQ87LsNxD5R1fbY8KYcKflHT+iaVzTZZaV/xH18NSQvxH0u0ntsL4lhkcbCYOwp99wM7TjEMhIvRf/mEZa9UnaLEpLT5GFShfj67Fy/G7w9WGoY+nH7XB6T1i62hySO3IIWM77rP6Z1myg5mCQ8PfmKF8FOHXY+/Q/nVbBSC/epYTHWHYf1mswUwRUTiVa/Tt/vCgrL7gQ8w7TiOC9tG1TF5PJcS0CZg0GK57xmThnoKUqFHckNzbuwQcQmQggmtdmWQ1mpMdcFtD3bH9l9pT8Fsnxig2YoZYdj/UbIvH1wvP4HrYfY59U3wXKGvviUs9jnyUIqi0ZkkUuRQOu8loMQN5N8TEBU=
