language: node_js
node_js:
    - stable
cache:
    directories:
        - node_modules
before_deploy:
    - yarn build
    - rm -rf node_modules/
jobs:
    include:
        - stage: Tests
          name: Lint
          script: yarn lint
        - stage: deploy
          if: branch = 48-deploy-ghpages
          name: Deploy to Github Pages
          script: skip
          deploy:
              provider: pages
              skip_cleanup: true
              github_token: '$github_token'
              local_dir: docs
              on:
                  branch: 48-deploy-ghpages
env:
    global:
        secure: vLoKgvUDlvrnHRRMfS3a4H0Td23QTinxcLuG/XqNsrfkC1e4B5ilLp4uY+fbebShEv0YCfVelhNHizj6RRULBpVx1t6RrUnbKRP06A/xAbhF/YpYzB6SUlIOuUrNJw0s0QPRMr5VOQIsT+LuKXYYQ5xzd/OwYO4eQoJKav+ubgQiv1bNFvlz8Ma8b9uRggNuJaxPyUVcD5nWEE3FqX1lAOAjezgozRaM/N6FaBWZglEQ3gt6DLbaGa1PUFKn6wpCD6/7vI89p3o0dZBCgn0xMh4IQT12Z5pcz/795750U5PTYS+AfzFyJSgn0AAc6/rsjd2xswzRGehm7ZTqDDdJ50viUhz7XsyMUbp4ZOmphZi/JbdRXOAIFhcWRmmfP9Ip6Dg7XVI3OgmeQL5yr6sJ0JQOtmUtnnFNB/BWccfNtBok/i3ka/3ghEx/sCVeOqTxj7hYxtqVZMP9roJ/cK3tIE+/73B2iU7qb056b9jb6nvD/OWz5B3+0xBGSLzrVERaHPXRFn07zZtIyoL9T5Ng3WEVZwX9/irCzJwIhTujyACZ1A0U/bd4tWkDLVIRf/xQELfHmQAVCenOc/EPBqdoUfMT1gmMWb6Xafe7exHswsamvTLa18g0eOxrGQH+DmmP70Zz4ejWbK52sG2J8DuImxHgkQlJRl/UufkzLgUCR7I=
