language: node_js
node_js:
    - stable
cache:
    directories:
        - node_modules
before_deploy:
    - yarn build
    - rm -rf node_modules/
jobs:
    include:
        - stage: Tests
          name: Lint
          script: yarn lint
        - stage: deploy
          if: branch = 48-deploy-ghpages
          name: Deploy to Github Pages
          script: skip
          deploy:
              provider: pages
              skip_cleanup: true
              github_token: '$github_token'
              local_dir: docs
              on:
                  branch: 48-deploy-ghpages
env:
    global:
        secure: G9VxsrYh/BMKcFACVIAduRRgAX2AUgYiJgKs8+48V9gg3tAzd/4Btn/YUAkpAirhgLmMab9IDRzdQAjlqYDLyVtOEwCom0C51gKRmO8gNzaWgwf5AqT505GcIQw4gqLwvkpNuGULKk2mVmedA+VdFzJctf4/ZUH2aTmSHGmizxBSveuNYP3yz7f+5jy4rHfEfw00KCLW99U787amdM8zekA8d/hOIogh7ds7sGHXNMt7QuVIXF4ARwnpd/zRRQ0IiYzMN4TPkVm9lXzVEkBu1lfIsDolnLg7my5UQVk1k9D3H1ElVtsv/X5awD1qQLJLPmsdXxmcXqn2spp0eQPGJvk9w1VMgaPCmMOXUYe7RQm9wlsQNKInW0E4qXvk+J6CYxTJJH3v+db9zkTjp/p6BfxpB7CH4UIRzKW6XWBGoMMlf3IFtd42D23eEBfTE1NVBEHEEjefgdXPtdNIa0Cf7KrZqiqUPu3ngLgZPNmpl5yar1WJDDYtPqHpQtzk/i3yD6QE25dbel8bQtJqRw7nF5ydRxDsPIIWzJQq5tFVthqmn8lR91pRjJ8xMYTvBW4SUMxHgdlv2nzPGJfI/Gz1ZsXCYbrtAM2wjsUBybI/7nCvj9KgAsCZVL9+ExxgnSDGuv8789d58nJ/NCFI4CsVxJHEDXan+oQxs3YLiMaANQ8=
