language: node_js
node_js:
    - stable
cache:
    directories:
        - node_modules
before_deploy:
    - yarn build
    - rm -rf node_modules/
jobs:
    include:
        - stage: Tests
          name: Lint
          script: yarn lint
        - stage: deploy
          if: branch = 48-deploy-ghpages
          name: Deploy to Github Pages
          script: skip
          deploy:
              provider: pages
              skip_cleanup: true
              github_token: '$github_token'
              local_dir: docs
              on:
                  branch: 48-deploy-ghpages
env:
    global:
        secure: WGNC8Itlcq6HcsS+XtaB0/ObxtjNt0FxiCwGaExoS7VbrQRh6npqS7jP3+umXLbWuMnUfxa4zixxNoxvBIs5RnkL5oT4lwPmRuSve9ZknHtAqAQn7FVfL9nBk8vqpwVexLepNsaUTB0tPlaW1UmfcZXElTIfHFQmJgNN2cGR+8wQkhHw3dKd+xk9jMZ6JXszb0y7Bf+KEdelhYLv2v4Z8p+MUDX6Rw5Fl3u2p51fEMdC6WH+xudDQKkp5KwYO3/296eKBRfiHq0Nx01pyGzNv/b4kEV6h0HUo0dvbVBBtdwlEdM8GVYR2GeilqORIpkBYVYg8QDvpic4Nu7JAwacShnJ/39MIpdHIDGm8nePUtdPgqoqnBH4rDct5O9xiRgy5IEtmS8th2XT0nsupprkrUtEf/5nIUfLd75kw61f9DNQxNikY+2m0N0/XBdbdrmaLattMAiqRhWWJ9IY7FB6shvCAJb7jLBmn0ruzNizU6cPxVPDAmWPR2OGsOZ7Jng5dJLptcJ0pW428ubnL4AaJfcTXhMVmyu4EV8ON1eNKg2YE4sTG9AGbK/XNjm7d8oPfA7YIdpHUjkw64/TqrbgQz876YOLxQDDJ3T4RAKD+scD4kWDTsxOB5Jpe41txFCtdGMj6avzNzSrfbDBNmQRDmP4BO+Q/6OhQCYFwLUyUIo=
