language: node_js
node_js:
    - node
    - lts/*
before_deploy:
    - yarn build
    - rm -rf node_modules/
jobs:
    include:
        - stage: Tests
          name: Lint
          script: yarn lint
        - stage: deploy
          if: branch = master
          name: Deploy to Github Pages
          script: skip
          deploy:
              provider: pages
              skip_cleanup: true
              github_token: '$GITHUB_TOKEN'
              keep-history: true
              local_dir: public
              fqdn: issueai.opendevufcg.org
              on:
                  branch: master
