language: node_js
node_js:
    - stable
cache:
    directories:
        - node_modules
before_deploy:
    - yarn build
    - rm -rf node_modules/
jobs:
    include:
        - stage: Tests
          name: Lint
          script: yarn lint
        - stage: deploy
          if: branch = 48-deploy-ghpages
          name: Deploy to Github Pages
          script: skip
          deploy:
              provider: pages
              skip_cleanup: true
              github_token: '$github_token'
              local_dir: docs
              on:
                  branch: 48-deploy-ghpages
env:
    global:
        secure: BuOQOj7j2N4/0+jCdfYkhmODmBsb4XgyrmEAJXpdb3PnSF37r08U2MDIBfMvwa6Tbt5AkoA1Lui3B4+FBYWsZX+2PoMfxpiCKcSWrvM/srYdgb0RCNzqXVqcjXdstpjdpcKQny1t19MoD1j+1m57Xk83XEIyxEff9LWut/Xq3tpT4MlA4/XMPAoepLM5WvxZo4QmxE+aquZpO6J3lwjH7OnJu7F2MO/1y3jJ/Wyrwbuo+XsurQmEby9DGh/7h/Mk0/LX19n6UqtD2/7f/nl8F8N7YZQfCwmzUvT4cMUr5UI0xESlN0seNg3Hy+Mo2We+L7T+13ZCAbIknG6SaCNdWCBz0MZD6bgh99fk6w01pY/UKjc+W3BsgISXvbdAyvYHUZHktLr+A33l9JDcadGoWAErVcUkIzkDm0wRR+6U1Jsv1hxvQmhbgD98YDHhyP9+z0ZsSWoj+4eCB4xwKiBzSm/dOawbKFplQs0RJ8Ni6BysZFrr8A3EQhyvGoBxJ+6QGPDw08mmwzZuKv43soRi+oRsOdPecjg96sFpIaMmVD09kz0SWKZvxVjOb/KXT7DdzmnIZ9i+WJpff+kpFmu0Xk55Awcho2uEIuaBfGoh38MBgM7VD/blmgxWL4lD9AJ1L8Hndidtow9cJ+vaHVku/duwecyhtY0xvzIgkq3AFEo=
